### ISSUE TITLE
Could a non-leader MultiprocessTimeSeries get the "max_length" from shared memory?

### ISSUE THREAD

**Issue by luator** [machines-in-motion/time_series#12]
@vincentberenz Not sure if this is as easy as I imagine it right now.  Would it be possible to store the length of the time series somewhere in the shared memory such that it would only need to be specified for the leader (the one which also takes care of cleaning up the memory).  Other clients could get the value from there so the user does not need to specify it.

This would make the usage easier and less error prone.  Right now, when changing the size, the change needs to be applied on all clients with somewhat undefined behaviour if the specified lengths do not match.

**Comment by vincentberenz** [comment]
@luator 

Turn out it was trivial to implement. Pull request ready for your review :)

**Comment by luator** [comment]
Implemented in #13.
